from wx.lib.embeddedimage import PyEmbeddedImage
#--------------------
ICON_BRUSH_CHECKERBOARD = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAABhGlDQ1BJQ0MgcHJvZmlsZQAA'
    b'KJF9kT1Iw0AcxV9TRdGKoB1EFDJUJwuioo5SxSJYKG2FVh1MLv2CJg1Jiouj4Fpw8GOx6uDi'
    b'rKuDqyAIfoA4OTopukiJ/0sKLWI8OO7Hu3uPu3eAUCsx1WwbB1TNMhLRiJjOrIodr+jGMPow'
    b'g4DETD2WXEzBc3zdw8fXuzDP8j735+hRsiYDfCLxHNMNi3iDeHrT0jnvEwdZQVKIz4nHDLog'
    b'8SPXZZffOOcdFnhm0Egl5omDxGK+heUWZgVDJZ4iDimqRvlC2mWF8xZntVRhjXvyFway2kqS'
    b'6zSHEMUSYohDhIwKiijBQphWjRQTCdqPePgHHX+cXDK5imDkWEAZKiTHD/4Hv7s1c5MTblIg'
    b'ArS/2PbHCNCxC9Srtv19bNv1E8D/DFxpTX+5Bsx+kl5taqEjoHcbuLhuavIecLkDDDzpkiE5'
    b'kp+mkMsB72f0TRmg/xboWnN7a+zj9AFIUVfLN8DBITCap+x1j3d3tvb275lGfz/C9XLHBWe9'
    b'TQAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+QLHRMANdxxlG0AAAAZdEVYdENvbW1l'
    b'bnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAA3klEQVR42u3WsQ2AMAwEwIAYJZNk/xEyDBOA'
    b'vkFfcN9abk629Mdaazxnzvky3Xv/avccEgcWLFiwYMESWLC+yaWj57suyxvCggULlsCCBavf'
    b'4HX0fNdleUNYsGDBEliwYPUbvI6e77osbwgLFixYAgsWrH6D19HzXZflDWHBggVLYMGC1W/w'
    b'Onq+67K8ISxYsGAJLFiw+g1eR893XZY3hAULFiyBBQtWv8Hr6Pmuy/KGsGDBgiWwYMHqN3gd'
    b'Pd91Wd4QFixYsAQWLFj9Bq+j57suyxvCggULlsCCBaueG25olQy7PmyzAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
ICON_IMAGE = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAeElEQVQ4jc3RUQ2AIBSFYSMY'
    b'hShEIAJNiGAEIxiFCET4ffDKGIpcfZGzMdgY384d0zRMgA194h0AsACuswJAC3CNdjNg5Gy/'
    b'AF7uTQ/wMoap7gywSpNHIBV7jVjNCGUyIs0Sx0+pgRMJRbPcUgs0MyYQX7xPF+C37Kkt3Df0'
    b'i7O6AAAAAElFTkSuQmCC')

